version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5001:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - network
    env_file: .env


networks:
  network:

#
# definition des volumes pour permettre une sauvegarde externe aux containers
#

volumes:
  pgdata:
    driver: local
    driver_opts:
      device: '${VOLUME_DB}'
      type: volume
      o: bind
      
