version: "3"

services:
  postgres:
    image: postgres
    restart: always
    #user: "${UID}:${GID}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./postgres/setupdb.sh:/docker-entrypoint-initdb.d/setupdb.sh:ro
    networks:
      - pg-network
    ports:
      - 5432:5432 # database port
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    init: true
    volumes:
      - ${PWD}/pgadmin/servers.json:/pgadmin4/servers.json:ro
    ports:
      - 5050:80
    networks:
      - pg-network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    depends_on:
      - postgres

  backend:
    build:
      context: ./docker
      dockerfile: ./backend.dockerfile
    init: true
    ports:
      - 3000:3000
      - 5555:5555 # prisma studio port
    networks:
      - pg-network
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: unless-stopped
    links:
      - postgres
    user: "${UID}:${GID}"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./docker
      dockerfile: ./frontend.dockerfile
    ports:
      - 5173:5173
    networks:
      - pg-network
    volumes:
      - ./frontend:/app
    environment:
      #WARNING: VARIABLES IN THE .ENV FILE CAN BE ACCESSED BY THE CLIENT
      #DO NOT put sensitive information (such as api keys or secrets) on the frontend container
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      VITE_PORT: ${FRONT_PORT}
    restart: unless-stopped
    #user: "${UID}:${GID}"
    depends_on:
      - backend

networks:
  pg-network:

volumes:
  pgdata:
    driver: local
    driver_opts:
      device: "${VOLUME_DB}"
      type: volume
      o: bind

#  backend:
  #   driver: local
  #   driver_opts:
  #     device: ${PWD}/backend
  #     type: volume
  #     o: bind

  # frontend:
  #   driver: local
  #   driver_opts:
  #     device: "${VOLUME_FRONT}"
  #     type: volume
  #     o: bind
