#!/bin/sh

dest=$1

echo "## This dotenv file is automatically generated by the build_dotenv.sh script, please DO NOT edit ##" > $dest

env >> $dest
url="postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_DB"
echo "DATABASE_URL=$url" >> $dest

echo "Dotenv file ($dest) generated"
