-- CreateEnum
CREATE TYPE "level_type" AS ENUM ('INITIATION', 'BEGINNER', 'INTERMEDIATE', 'EXPERT');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "level" "level_type" NOT NULL DEFAULT 'INITIATION',
ADD COLUMN     "nbGames" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "nbMatch" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rank" INTEGER NOT NULL DEFAULT 0;
